### ISSUE TITLE
Testing files are missing

### ISSUE THREAD

**Issue by tanov25** [git-disl/BERT4ETH#1]
Hello,
It would be very nice of you if you added the testing files that are mentioned in the README.md.
Thanks.

**Comment by Bayi-Hu** [comment]
Sorry for the missing. I uploaded the label for the phishing account, ENS pair and Tornado pairs. I also uploaded the transactions for Tornado accounts. MEV bot dataset is not used in our camera-ready paper. 

For directions running the code, you can find in Model/data_generation.sh and Model/BERT4ETH/run_bert.sh.
