### ISSUE TITLE
FileNotFoundError: No such file or directory: './Data/tornado_raw_data/tornadoFullHistoryMixer_0.1ETH.csv'

### ISSUE THREAD

**Issue by yuyan110nan** [git-disl/BERT4ETH#10]
When I run python run_dean_Tornado.py, I find a FileNotFoundError: No such file or directory: './Data/tornado_raw_data/tornadoFullHistoryMixer_0.1ETH.csv', 
and I can't find this file in the/Data directory. 
So, how can I find tornadoFullHistoryMixer_0.1ETH.csv?

**Comment by Sorrow-Knight** [comment]
same question.

**Comment by Bayi-Hu** [comment]
I will update the file soon, thanks!

**Comment by Bayi-Hu** [comment]
Hi, I have uploaded missing files, Thanks.
