### ISSUE TITLE
  May I ask if there is a problem with my tf version

### ISSUE THREAD

**Issue by yuanomg** [git-disl/BERT4ETH#3]
i try to run code in my local enveriment，but i have some version problem.

"TypeError: __init__() got multiple values for argument 'activation'"
when i try to run the "run_pretrain.py".
 i try 1.x tf and 2.x tf all can not work.

**Comment by YQzQY** [comment]
i try 1.15.4, it can work

**Comment by H0uzC** [comment]
> i try 1.15.4, it can work

@YQzQY
Did you meet the "Out of range: End of sequence" issue when you run run_pretrain.py?


```txt
iter=152900, loss=0.000002, time=4.56s
iter=153000, loss=0.000003, time=4.57s
iter=153100, loss=0.000003, time=4.57s
Out of Sequence, end of training...
2 root error(s) found.
  (0) Out of range: End of sequence
	 [[node IteratorGetNext (defined at run_pretrain.py:162) ]]
	 [[IteratorGetNext/_39]]
  (1) Out of range: End of sequence
	 [[node IteratorGetNext (defined at run_pretrain.py:162) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 OneShotIterator (defined at run_pretrain.py:161)

Input Source operations connected to node IteratorGetNext:
 OneShotIterator (defined at run_pretrain.py:161)

Original stack trace for 'IteratorGetNext':
  File "run_pretrain.py", line 688, in <module>
    tf.app.run()
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_pretrain.py", line 574, in main
    features = input_fn(input_files, is_training=True)
  File "run_pretrain.py", line 162, in input_fn
    features = iterator.get_next()
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 415, in get_next
    flat_ret = gen_dataset_ops.iterator_get_next(
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2599, in iterator_get_next
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "/home/bert4eth/anaconda3/envs/bert4eth/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by Bayi-Hu** [comment]
"Out of range: End of sequence" error indicates that the pre-training has reached its end.

**Comment by H0uzC** [comment]
> "Out of range: End of sequence" error indicates that the pre-training has reached its end.

Does that mean the pre-training is complete?

**Comment by Bayi-Hu** [comment]
Yes.

**Comment by Bayi-Hu** [comment]
Hello,

I have reorganized the code and tested it. The code should be able to reproduce the results presented in the paper.

Thank you,
Sihao

**Comment by Bayi-Hu** [comment]
> i try to run code in my local enveriment，but i have some version problem.
> 
> "TypeError: **init**() got multiple values for argument 'activation'" when i try to run the "run_pretrain.py". i try 1.x tf and 2.x tf all can not work.

Actually I use python 3.9, tensorflow 2.9.2 with CUDA 11.2.
I am also trying to convert the code to the pytorch version.

**Comment by Bayi-Hu** [comment]
> > "Out of range: End of sequence" error indicates that the pre-training has reached its end.
> 
> Does that mean the pre-training is complete?

You can directly output the embedding by specify the stored checkpoint.

**Comment by H0uzC** [comment]
> > i try to run code in my local enveriment，but i have some version problem.
> > "TypeError: **init**() got multiple values for argument 'activation'" when i try to run the "run_pretrain.py". i try 1.x tf and 2.x tf all can not work.
> 
> Actually I use python 3.9, tensorflow 2.9.2 with CUDA 11.2. I am also trying to convert the code to the pytorch version.


> > > "Out of range: End of sequence" error indicates that the pre-training has reached its end.
> > 
> > 
> > Does that mean the pre-training is complete?
> 
> You can directly output the embedding by specify the stored checkpoint.

Thank You！
That helps me a lot.
Looking forward to your pytorch version.🤩

**Comment by Bayi-Hu** [comment]
> > > i try to run code in my local enveriment，but i have some version problem.
> > > "TypeError: **init**() got multiple values for argument 'activation'" when i try to run the "run_pretrain.py". i try 1.x tf and 2.x tf all can not work.
> > 
> > 
> > Actually I use python 3.9, tensorflow 2.9.2 with CUDA 11.2. I am also trying to convert the code to the pytorch version.
> 
> > > > "Out of range: End of sequence" error indicates that the pre-training has reached its end.
> > > 
> > > 
> > > Does that mean the pre-training is complete?
> > 
> > 
> > You can directly output the embedding by specify the stored checkpoint.
> 
> Thank You！ That helps me a lot. Looking forward to your pytorch version.🤩

I also reorganized the code to make it simpler. Apologize for the delayed response during the summer since I was sick for several weeks and didn't work.

**Comment by H0uzC** [comment]
> > > > i try to run code in my local enveriment，but i have some version problem.
> > > > "TypeError: **init**() got multiple values for argument 'activation'" when i try to run the "run_pretrain.py". i try 1.x tf and 2.x tf all can not work.
> > > 
> > > 
> > > Actually I use python 3.9, tensorflow 2.9.2 with CUDA 11.2. I am also trying to convert the code to the pytorch version.
> > 
> > 
> > > > > "Out of range: End of sequence" error indicates that the pre-training has reached its end.
> > > > 
> > > > 
> > > > Does that mean the pre-training is complete?
> > > 
> > > 
> > > You can directly output the embedding by specify the stored checkpoint.
> > 
> > 
> > Thank You！ That helps me a lot. Looking forward to your pytorch version.🤩
> 
> I also reorganized the code to make it simpler. Apologize for the delayed response during the summer since I was sick for several weeks and didn't work.

Oh I'm sorry to hear that. 🥲
I have updated your optimization of the project in my local code, thank you very much for your efforts. 
Wish you good health.

**Comment by ll72** [comment]
Code debugging should be your own responsibility. We open source code but not help others to learn how to run the release. This is the same for all open source projects.

Also  BERT4ETH has been tested by others outside our group and it works smoothly.


From: kururu ***@***.***>
Date: Wednesday, August 30, 2023 at 12:08 PM
To: git-disl/BERT4ETH ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [git-disl/BERT4ETH] May I ask if there is a problem with my tf version (Issue #3)

i try to run code in my local enveriment，but i have some version problem.
"TypeError: init() got multiple values for argument 'activation'" when i try to run the "run_pretrain.py". i try 1.x tf and 2.x tf all can not work.

Actually I use python 3.9, tensorflow 2.9.2 with CUDA 11.2. I am also trying to convert the code to the pytorch version.

"Out of range: End of sequence" error indicates that the pre-training has reached its end.

Does that mean the pre-training is complete?

You can directly output the embedding by specify the stored checkpoint.

Thank You！ That helps me a lot. Looking forward to your pytorch version.🤩

I also reorganized the code to make it simpler. Apologize for the delayed response during the summer since I was sick for several weeks and didn't work.

Oh I'm sorry to hear that. 🥲
I have updated your optimization of the project in my local code, thank you very much for your efforts.
Wish you good health.
