### ISSUE TITLE
array has an inhomogeneous shape after 1 dimensions.

### ISSUE THREAD

**Issue by poupou-web3** [git-disl/BERT4ETH#6]
Hello,

I'm getting that error when running 
`python gen_pretrain_data.py --bizdate=bert4eth_exp  --max_seq_length=100  --dupe_factor=10 --masked_lm_prob=0.8`

```
Traceback (most recent call last):
  File "$PATH\BERT4ETH\Model\gen_pretrain_data.py", line 448, in <module>
    main()
  File "$PATH\BERT4ETH\Model\gen_pretrain_data.py", line 402, in main
    seqs = np.random.permutation(seqs)
  File "mtrand.pyx", line 4703, in numpy.random.mtrand.RandomState.permutation
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (631617,) + inhomogeneous part.
```

**Comment by H0uzC** [comment]
What's the verion of your numpy?
I am using numpy==1.23.4 and it works

**Comment by H0uzC** [comment]
> Hello,
> 
> I'm getting that error when running `python gen_pretrain_data.py --bizdate=bert4eth_exp --max_seq_length=100 --dupe_factor=10 --masked_lm_prob=0.8`
> 
> ```
> Traceback (most recent call last):
>   File "$PATH\BERT4ETH\Model\gen_pretrain_data.py", line 448, in <module>
>     main()
>   File "$PATH\BERT4ETH\Model\gen_pretrain_data.py", line 402, in main
>     seqs = np.random.permutation(seqs)
>   File "mtrand.pyx", line 4703, in numpy.random.mtrand.RandomState.permutation
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (631617,) + inhomogeneous part.
> ```

What's the version of your numpy?
I am using numpy==1.23.4 and it works

**Comment by Bayi-Hu** [comment]
My numpy version is 1.19.5.

**Comment by poupou-web3** [comment]
Thank you using `numpy-1.23.4` fixed the issue.
