### ISSUE TITLE
Classification of Sybils

### ISSUE THREAD

**Issue by epowell101** [git-disl/BERT4ETH#7]
I'm wondering whether we should add a classifier and then train that and 1 or 2 layers of bert4eth using our data set of labels or would it make more sense to somehow use the deanonamization as demonstrated w the ENS example as a first step, perhaps checking to see if it predicted these labels.

Any suggestions would be great as of course the permutations are vast - and time is short

**Comment by Bayi-Hu** [comment]
I think you can first try phishing account detection (fixed training & fine-tuning) because it is more similar to the sybils detection task. You can then use your own dataset for experiment. Thanks.
