### ISSUE TITLE
 Hello, author. I encountered this "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 68: invalid continuation byte" when I was copying the code. Can you reply to me?

### ISSUE THREAD

**Issue by brainplait** [git-disl/BERT4ETH#8]

**Comment by Bayi-Hu** [comment]
which file did you meet this problem? Check the 68 line of that file and see what's going on.

**Comment by brainplait** [comment]
> 您是哪个文件遇到这个问题的？检查该文件的第 68 行，看看发生了什么。


Thank you very much for your answer! I'll pay attention to this file.

**Comment by Bayi-Hu** [comment]
Let me know if the problem is not fixed : )
